spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:notiondb
    initialization-mode: always
  h2:
    console:
      enabled: True
  sql:
    init:
      mode: always