spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:notiondb
  h2:
    console:
      enabled: True
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql
