spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:notiondb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: True