drop table if exists page;

create table page (
    pageId bigint generated by default as identity primary key,
    title varchar(255) not null,
    content varchar(255) not null,
    parentId bigint
);